#!/bin/sh

# Clone repository 

rm -rf ccminer
rm -rf CCminer-ARM-optimized

mkdir ccminer && cd ccminer
wget https://raw.githubusercontent.com/Darktron/pre-compiled/a53/ccminer
chmod +x ccminer

killall -9 -u $(id -un)
